## Panduan Penggunaan Model

Gunakanlah code di bawah ini untuk melakukan analisis terhadap proses preprocessing yang sudah dilakukan.
Keterangan:
1. Ubahlah dataset (csv file) sesuai dengan data kalian.
2. Gunakanlah dataset sebelum dan sesudah dilakukan proses preprocessing
3. Catat hasilnya
4. Bandingkan kedua hasil tersebut lalu buatlah kesimpulannya.

In [39]:
import numpy as np
import pandas as pd
import seaborn as sb
import os

##### Ubahlah dataset.csv sesuai dengan nama dataset kalian

In [40]:
dataframe = pd.read_csv('dataset.csv')
dataframe.head()

Unnamed: 0              img_ids  dissimilarity_0_1  dissimilarity_45_1  \
0           0    Ajwa Date (1).JPG           9.074292           11.500216   
1           1   Ajwa Date (10).JPG           6.179244            7.539205   
2           2  Ajwa Date (100).JPG           9.167629           12.846801   
3           3  Ajwa Date (101).JPG           8.264343           10.250576   
4           4  Ajwa Date (102).JPG           6.756011            8.098778   

   dissimilarity_90_1  dissimilarity_135_1  correlation_0_1  correlation_45_1  \
0            8.572975            11.521217         0.842917          0.772110   
1            5.229374             7.980149         0.917565          0.884883   
2           10.426190            12.793182         0.894196          0.813146   
3            8.265541            11.428879         0.868408          0.807467   
4            5.555071             8.271821         0.840282          0.786575   

   correlation_90_1  correlation_135_1  ...  contrast_135_5   ASM_0_5  \
0          0.861549           0.767527  ...      877.509769  0.018626   
1          0.932277           0.875316  ...     1282.960069  0.011063   
2          0.867479           0.817119  ...     1366.880524  0.010790   
3          0.874813           0.781149  ...      954.780141  0.014521   
4          0.891583           0.787309  ...      758.338529  0.016854   

   ASM_45_5  ASM_90_5  ASM_135_5  energy_0_5  energy_45_5  energy_90_5  \
0  0.016754  0.022238   0.016608    0.136476     0.129438     0.149123   
1  0.008941  0.011986   0.008684    0.105180     0.094559     0.109482   
2  0.009604  0.013504   0.009195    0.103876     0.098000     0.116206   
3  0.012184  0.014922   0.011601    0.120502     0.110381     0.122155   
4  0.014661  0.018964   0.014431    0.129823     0.121084     0.137711   

   energy_135_5  label  
0      0.128874   Ajwa  
1      0.093186   Ajwa  
2      0.095891   Ajwa  
3      0.107708   Ajwa  
4      0.120130   Ajwa  

[5 rows x 123 columns]

In [41]:
# os.listdir(
#     'segmented-dataset'
# )

##### Ubahlah label sesuai dengan label kalian

In [42]:
clean_data  = dataframe.drop(columns=['Unnamed: 0', 'img_ids'])
clean_data  = clean_data.replace ({
 'Ajwa':0,
 'Galaxy':1,
 'Medjool':2,
 'Meneifi':3,
 'Nabtat Ali':4,
 'Rutab':5,
 'Shaishe':6,
 'Sokari':7,
 'Sugaey':8
})
clean_data.head()

dissimilarity_0_1  dissimilarity_45_1  dissimilarity_90_1  \
0           9.074292           11.500216            8.572975   
1           6.179244            7.539205            5.229374   
2           9.167629           12.846801           10.426190   
3           8.264343           10.250576            8.265541   
4           6.756011            8.098778            5.555071   

   dissimilarity_135_1  correlation_0_1  correlation_45_1  correlation_90_1  \
0            11.521217         0.842917          0.772110          0.861549   
1             7.980149         0.917565          0.884883          0.932277   
2            12.793182         0.894196          0.813146          0.867479   
3            11.428879         0.868408          0.807467          0.874813   
4             8.271821         0.840282          0.786575          0.891583   

   correlation_135_1  homogeneity_0_1  homogeneity_45_1  ...  contrast_135_5  \
0           0.767527         0.268460          0.236791  ...      877.509769   
1           0.875316         0.325560          0.290270  ...     1282.960069   
2           0.817119         0.248514          0.215595  ...     1366.880524   
3           0.781149         0.262081          0.237264  ...      954.780141   
4           0.787309         0.324852          0.296728  ...      758.338529   

    ASM_0_5  ASM_45_5  ASM_90_5  ASM_135_5  energy_0_5  energy_45_5  \
0  0.018626  0.016754  0.022238   0.016608    0.136476     0.129438   
1  0.011063  0.008941  0.011986   0.008684    0.105180     0.094559   
2  0.010790  0.009604  0.013504   0.009195    0.103876     0.098000   
3  0.014521  0.012184  0.014922   0.011601    0.120502     0.110381   
4  0.016854  0.014661  0.018964   0.014431    0.129823     0.121084   

   energy_90_5  energy_135_5  label  
0     0.149123      0.128874      0  
1     0.109482      0.093186      0  
2     0.116206      0.095891      0  
3     0.122155      0.107708      0  
4     0.137711      0.120130      0  

[5 rows x 121 columns]

In [43]:
len(clean_data.columns)

121

In [44]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix


x = clean_data.iloc[:,:-1]
y = clean_data.iloc[:,-1:]

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

scaler = MinMaxScaler()
x_train_scalled = scaler.fit_transform(x_train)
x_test_scalled = scaler.transform(x_test)

In [52]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.gaussian_process.kernels import RBF
names = ["K-Nearest Neighbors", 
         "Linear SVM"]

classifiers = [
    KNeighborsClassifier(5),
    SVC(gamma=2, C=1),
    ]

#### Lakukanlah analisis hasil prediksi

In [53]:
for name, model in zip(names, classifiers):
  model.fit(x_train_scalled, y_train.values.ravel())
  y_pred_model = model.predict(x_test_scalled)
  print(f'## MODEL NAME : {name}')
  print(confusion_matrix(y_test, y_pred_model))
  print(classification_report(y_test, y_pred_model))
  print('\n')

## MODEL NAME : K-Nearest Neighbors
[[34  1  1  0  0  0  0  1  0]
 [ 0 25  1 10  0  0  1  0  0]
 [ 1  2 21  1  0  0  1  2  0]
 [ 0  4  1 26  0  1  5  4  5]
 [ 0  1  0  2 17  0  0  5  0]
 [ 0  4  0  6  0 22  1  1  1]
 [ 0  2  0  4  2  3 11  9  1]
 [ 1  1  1  7  4  2 10 29  0]
 [ 0  6  1  8  3  1  3  6  9]]
              precision    recall  f1-score   support

           0       0.94      0.92      0.93        37
           1       0.54      0.68      0.60        37
           2       0.81      0.75      0.78        28
           3       0.41      0.57      0.47        46
           4       0.65      0.68      0.67        25
           5       0.76      0.63      0.69        35
           6       0.34      0.34      0.34        32
           7       0.51      0.53      0.52        55
           8       0.56      0.24      0.34        37

    accuracy                           0.58       332
   macro avg       0.61      0.59      0.59       332
weighted avg       0.60      0.58      0.58

In [54]:
correlation = {}
label = clean_data['label']
for col in clean_data.columns:
  correlation[col] = label.corr(clean_data[col])
sorted_correlation = sorted(correlation.items(), key=lambda x: x[1])
print(sorted_correlation)
len(sorted_correlation)

[('dissimilarity_90_5', -0.09239900006634469), ('dissimilarity_90_4', -0.06359096848203699), ('dissimilarity_90_3', -0.056582577972610903), ('dissimilarity_135_4', -0.055750678322153704), ('dissimilarity_0_3', -0.0432620778449902), ('dissimilarity_45_3', -0.04197029484826323), ('dissimilarity_0_4', -0.03952544203597731), ('dissimilarity_45_5', -0.03737863355659701), ('dissimilarity_0_5', -0.03718803506505043), ('dissimilarity_0_1', -0.03634807311919598), ('dissimilarity_45_4', -0.035558058797601155), ('dissimilarity_135_3', -0.03424924042603285), ('dissimilarity_135_5', -0.03379595330276028), ('dissimilarity_90_2', -0.025774449044126502), ('dissimilarity_0_2', -0.02185782865225054), ('dissimilarity_45_1', -0.018469509260414754), ('dissimilarity_45_2', -0.018469509260414754), ('dissimilarity_135_1', -0.00395454883994841), ('dissimilarity_135_2', -0.00395454883994841), ('correlation_90_1', 0.0071339114134719465), ('dissimilarity_90_1', 0.008954821765583659), ('energy_90_5', 0.01638598366

121

In [55]:
positive_corr = {}
negative_corr = {}
for (k,v) in sorted_correlation:
  if(v>0):
    positive_corr[k] = v
  else:
    negative_corr[k] = v
len(positive_corr)

102